---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./jellyfin/ks.yaml
  - ./plex/ks.yaml
  - ./tautulli/ks.yaml
  - ./sickchill/ks.yaml
  - ./jdownloader/ks.yaml
  - ./plex-ripper/ks.yaml
#  - ./vlc-telnet/ks.yaml
