---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./csi-driver-nfs.yaml
  - ./external-dns.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./jetstack.yaml
  - ./kubernetes-dashboard.yaml
  - ./metrics-server.yaml
  - ./prometheus-community.yaml
  - ./openebs.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
  - ./piraeus.yaml
  - ./node-feature-discovery.yaml
  - ./intel.yaml
  - ./backube.yaml
  - ./cloudnative-pg.yaml
  - ./emqx-charts.yaml
  - ./grafana-charts.yaml
  - ./rook-ceph-charts.yaml
  - ./truecharts.yaml
  - ./vmware-tanzu-charts.yaml
  - ./k8s-at-home-charts.yaml
  - ./kyverno.yaml
  - ./influxdata-charts.yaml
  - ./lwolf-charts.yaml
  - ./runix.yaml
  - ./external-secrets.yaml
  - ./descheduler.yaml
  - ./nextcloud-charts.yaml
