---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-restic-secret
  namespace: observability
type: Opaque
stringData:
  RESTIC_REPOSITORY: "${S3_RESTIC_URL}/influxdb"
  RESTIC_PASSWORD: "${RESTIC_PASSWORD}"
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"

---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: influxdb
  namespace: observability
spec:
  sourcePVC: influxdb-data
  trigger:
    schedule: "0 22 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: influxdb-restic-secret
    cacheCapacity: 2Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    #https://volsync.readthedocs.io/en/stable/design/restic.html
    retain:
      hourly: 24
      daily: 30
      weekly: 52
      monthly: 12
      yearly: 10
